# file:     makefile:
# author:   ntietz
# date:     2011.5.26

# A makefile for building the SOOGSAL project.
# 
# SYNOPSIS:
# 
#   make [all]		- makes everything and runs the tests
#	make compile	- just builds the source
#	make run_tests	- just runs the tests
#	make TARGET		- makes the given target
#	make clean		- removes all files generated by make

COMPILER=g++
# COMPILER=clang
COMPILE_OPTS= -std=gnu++0x -Wall -ggdb -I${SRC} -Ilib #adds c++0x support, for the random lib
SRC_DIR = src
SRC=src
BIN=bin

GTEST_DIR = lib/gtest-1.6.0
TEST_DIR = test
TEST_FLAGS = ${COMPILE_OPTS} -I${GTEST_DIR} -I${GTEST_DIR}/include
TESTS = chromosomeTest.o quicksortTest.o

GTEST_HEADERS = ${GTEST_DIR}/include/gtest/*.h \
				${GTEST_DIR}/include/gtest/internal/*.h

GTEST_SRCS = ${GTEST_DIR}/src/*.cc ${GTEST_DIR}/src/*.h ${GTEST_HEADERS}

# META TARGETS

all : clean init compile build_tests run_tests
	

init :
	mkdir bin

compile : chromosome random datagen mergesort bubblesort quicksort converter ga
	

build_tests : tests
	

run_tests : build_tests
	bin/tests.out

#
# SOURCE TARGETS
#

mergesort: ${SRC}/common.h ${SRC}/merge/mergesort.h
	${COMPILER} ${COMPILE_OPTS} ${SRC}/merge/mergesort.h

bubblesort: ${SRC}/common.h ${SRC}/bubble/bubblesort.h
	${COMPILER} ${COMPILE_OPTS} ${SRC}/bubble/bubblesort.h

#TODO add dependencies to the following targets

quicksort :
	${COMPILER} ${COMPILE_OPTS} ${SRC}/quick/quicksort.h

chromosome : ${SRC}/chromosome/chromosome.cpp ${SRC}/chromosome/chromosome.hpp
	${COMPILER} ${COMPILE_OPTS} ${SRC}/chromosome/chromosome.cpp -c -o ${BIN}/chromosome.o

converter : ${SRC}/converter/converter.hpp
	${COMPILER} ${COMPILE_OPTS} ${SRC}/converter/converter.hpp -c -o ${BIN}/converter.o

random : lib/SimpleRNG.h lib/SimpleRNG.cpp
	${COMPILER} ${COMPILE_OPTS} lib/SimpleRNG.cpp -c -o ${BIN}/random.o

datagen : src/datagen/datagen.cpp src/datagen/datagen.hpp
	${COMPILER} ${COMPILE_OPTS} src/datagen/datagen.cpp -c -o ${BIN}/datagen.o

ga : src/ga/ga.h
	${COMPILER} ${COMPILE_OPTS} src/ga/ga.h -c -o ${BIN}/ga.o

# 
# UNIT TEST TARGETS
#

gtest-all.o : ${GTEST_SRCS}
	${COMPILER} ${TEST_FLAGS} -c ${GTEST_DIR}/src/gtest-all.cc

gtest_main.o : ${GTEST_SRCS}
	${COMPILER} ${TEST_FLAGS} -c ${GTEST_DIR}/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

chromosomeTest.o : ${TEST_DIR}/chromosomeTest.cpp chromosome ${GTEST_HEADERS}
	${COMPILER} ${TEST_FLAGS} -c ${TEST_DIR}/chromosomeTest.cpp

quicksortTest.o : ${TEST_DIR}/quicksortTest.cpp quicksort ${GTEST_HEADERS}
	${COMPILER} ${TEST_FLAGS} -c ${TEST_DIR}/quicksortTest.cpp

LINKS = bin/*.o
tests : ${TESTS} gtest_main.a 
	${COMPILER} ${TEST_FLAGS} -lpthread $^ bin/chromosome.o -o bin/$@.out

#
# CLEAN
#

clean : 
	rm -f */*/*.h.gch
	rm -rf bin
	rm -f *.o
	rm -f *.a

